services:
  postgres:
    image: postgres:15
    container_name: job_postgres
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: job_app
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: on-failure

volumes:
  postgres_data: